#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import platform
import shutil
import sys
import tomllib
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from fusion_reader_v2.owned_subprocess import run_owned  # noqa: E402

OUTPUTS = {
    "handoff": ROOT / "docs/HANDOFF_CODEX_2026-07-12.md",
    "consolidation": ROOT / "docs/CONSOLIDATION_FINAL_2026-07-12.md",
    "inventory": ROOT / "docs/audits/FINAL_CHANGE_INVENTORY_2026-07-12.md",
    "architecture": ROOT / "docs/audits/ARCHITECTURE_BEFORE_AFTER_2026-07-12.md",
}


def command(*args: str) -> str:
    result = run_owned(args, cwd=ROOT, timeout=30.0, text=True, check=True)
    return str(result.stdout or "").strip()


def optional_command(*args: str) -> str:
    try:
        return command(*args)
    except Exception:
        return ""


def coverage_metadata(path: Path | None) -> dict:
    if path is None or not path.is_file():
        return {"state": "not_observed"}
    try:
        report = json.loads(path.read_text(encoding="utf-8"))
        totals = report["totals"]
        return {
            "state": "observed_local",
            "lines": float(totals["percent_covered"]),
            "branches": (
                100.0
                if int(totals.get("num_branches", 0)) == 0
                else int(totals.get("covered_branches", 0)) * 100.0 / int(totals["num_branches"])
            ),
        }
    except (OSError, KeyError, TypeError, ValueError, json.JSONDecodeError):
        return {"state": "invalid_report"}


def github_metadata(pr: int) -> dict:
    if not shutil.which("gh"):
        return {"state": "not_observed", "reason": "gh unavailable"}
    raw = optional_command(
        "gh",
        "pr",
        "view",
        str(pr),
        "--json",
        "number,state,isDraft,mergeable,headRefOid,baseRefOid,headRefName,baseRefName,url",
    )
    if not raw:
        return {"state": "not_observed", "reason": "gh unavailable or unauthenticated"}
    try:
        payload = json.loads(raw)
    except json.JSONDecodeError:
        return {"state": "invalid_response"}
    payload["state_source"] = "observed_github"
    checks = optional_command("gh", "pr", "checks", str(pr), "--json", "name,state,link")
    if checks:
        try:
            payload["checks"] = json.loads(checks)
        except json.JSONDecodeError:
            payload["checks"] = []
    return payload


def collect_metadata(args: argparse.Namespace) -> dict:
    base_ref = args.base
    head = command("git", "rev-parse", "HEAD")
    base = command("git", "rev-parse", base_ref)
    branch = command("git", "branch", "--show-current")
    short_log = command("git", "log", "--format=%h %s", f"{base_ref}..HEAD")
    numstat = command("git", "diff", "--numstat", f"{base_ref}...HEAD")
    rows = [line.split("\t", 2) for line in numstat.splitlines() if line.strip()]
    additions = sum(int(row[0]) for row in rows if row[0].isdigit())
    deletions = sum(int(row[1]) for row in rows if row[1].isdigit())
    pyproject = tomllib.loads((ROOT / "pyproject.toml").read_text(encoding="utf-8"))
    return {
        "generated_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "git": {
            "branch": branch,
            "head_observed_before_generation": head,
            "base_ref": base_ref,
            "base": base,
            "commit_count": int(command("git", "rev-list", "--count", f"{base_ref}..HEAD")),
            "changed_files": len(rows),
            "additions": additions,
            "deletions": deletions,
            "commits": short_log.splitlines(),
            "files": [row[2] for row in rows],
        },
        "local": {
            "tests": args.tests,
            "coverage": coverage_metadata(args.coverage_json),
            "python": platform.python_version(),
            "node": optional_command("node", "--version") or "not_observed",
            "package_version": pyproject["project"]["version"],
        },
        "github": github_metadata(args.pr),
        "human": {
            "license": "decision required; see docs/LICENSING_DECISION_REQUIRED.md",
            "branch_protection": "post-merge maintainer action; not performed",
            "merge": "forbidden by ticket; not performed",
        },
        "risks": list(args.risk) or ["No unresolved risk supplied to the generator."],
    }


def common_header(title: str, data: dict) -> str:
    git = data["git"]
    return (
        f"# {title}\n\n"
        "> Generated by `scripts/generate_handoff.py`. Git values describe the clean input commit observed before "
        "these generated files are committed; GitHub values are separately labeled.\n\n"
        f"- Generated UTC: `{data['generated_at']}`\n"
        f"- Branch (Git): `{git['branch']}`\n"
        f"- Head observed before generation (Git): `{git['head_observed_before_generation']}`\n"
        f"- Base ref / SHA (Git): `{git['base_ref']}` / `{git['base']}`\n"
        f"- Diff (Git): {git['commit_count']} commits, {git['changed_files']} files, "
        f"+{git['additions']} / -{git['deletions']}\n"
    )


def render(data: dict) -> dict[Path, str]:
    git, local, github = data["git"], data["local"], data["github"]
    github_text = json.dumps(github, ensure_ascii=False, indent=2, sort_keys=True)
    risks = "\n".join(f"- {item}" for item in data["risks"])
    services = "ReaderService, AudioService, PreparationService, AudioExportService, DialogueService, ResearchService, NotesService, SessionPersistenceService and BackgroundLifecycleService"
    handoff = (
        common_header("Handoff Codex — Fusion Reader v2 / PR #13", data)
        + f"""

## Observed locally

- Test result supplied to generator: `{local["tests"]}`.
- Coverage: `{json.dumps(local["coverage"], ensure_ascii=False, sort_keys=True)}`.
- Python: `{local["python"]}`; Node: `{local["node"]}`; package: `{local["package_version"]}`.
- Public facade: `fusion_reader_v2.facade.FusionReaderV2`; `service.py` is compatibility-only.
- Extracted services: {services}.
- HTTP is local-only; non-loopback configuration is rejected and no remote token is used.

## Observed on GitHub

```json
{github_text}
```

## Human checklist / pending decisions

- License remains undecided: `docs/LICENSING_DECISION_REQUIRED.md`.
- PR must remain open and must not be merged or auto-merged by this work.
- Branch protection is a maintainer action after merge, outside this ticket.

## Risks supplied at generation

{risks}
"""
    )
    consolidation = (
        common_header("Consolidación final de Fusion Reader v2", data)
        + f"""

## Architecture after consolidation

- `FusionReaderV2` is the public composition facade and delegates bounded state to {services}.
- `fusion_reader_v2/service.py` preserves the historic import without product logic.
- Web request domains live in route modules and are dispatched by `routing.py`.
- The browser has one entry point and ES modules for API, UI, busy state, audio, audio export, preparation, notes and dialogue state.
- CSP rejects inline script/style execution; HTTP remains loopback-only.

## Reproducibility and quality gates

- Python 3.11 and 3.12 have separate pinned constraints consumed by CI.
- Global and critical coverage gates consume `coverage.json` and fail independently.
- Subprocess execution in active paths uses the owned-process helper.
- ZIP/document limits and atomic output publication are covered by unit and integration tests.

## Evidence boundaries

- Local test observation: `{local["tests"]}`.
- GitHub observation: `{github.get("state_source", github.get("state", "not_observed"))}`.
- Nightly is not claimed green unless present as a successful check in the GitHub JSON above.
"""
    )
    inventory = (
        common_header("Final change inventory", data)
        + "\n\n## Changed files (Git)\n\n"
        + "\n".join(f"- `{name}`" for name in git["files"])
        + "\n\n## Commits (Git)\n\n"
        + "\n".join(f"- `{item}`" for item in git["commits"])
        + "\n"
    )
    architecture = (
        common_header("Architecture before / after", data)
        + f"""

| Area | Before | After |
|---|---|---|
| Public application | `service.py` monolith | `facade.py` public facade plus compatibility import |
| Product services | Shared facade-owned state | {services} with explicit dependencies |
| HTTP | Large handler dispatch | Router-dispatched domain route modules, bounded jobs/download helpers |
| Frontend | Single application script | One entry plus responsibility-based ES modules |
| Security | Mixed future-remote signals | Loopback-only configuration, strict CSP, bounded imports/outputs |
| Reproducibility | Unpinned development installs | Python 3.11/3.12 constraints used by CI |
| Quality | Global percentage only | Global plus per-critical-module line/branch enforcement |

The historical prototype remains compatibility/laboratory reference; active product code remains under `fusion_reader_v2/`.
"""
    )
    return {
        OUTPUTS["handoff"]: handoff,
        OUTPUTS["consolidation"]: consolidation,
        OUTPUTS["inventory"]: inventory,
        OUTPUTS["architecture"]: architecture,
    }


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate final PR #13 handoff documents from observed evidence.")
    parser.add_argument("--base", default="origin/main")
    parser.add_argument("--pr", type=int, default=13)
    parser.add_argument("--tests", default="not_observed")
    parser.add_argument("--coverage-json", type=Path)
    parser.add_argument("--risk", action="append", default=[])
    return parser.parse_args()


def main() -> int:
    outputs = render(collect_metadata(parse_args()))
    for path, content in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content.rstrip() + "\n", encoding="utf-8")
        print(path.relative_to(ROOT))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
